version: '2.4'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.${SUBNET}.0/24
services:
  db:
    image: postgres:${POSTGRES_VERSION:-10.6}
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - back
  app:
    image: hackmd/hackmd:${CODIMD_VERSION:-1.2.1}
    env_file: .env
    volumes:
      - ./data/uploads:/hackmd/public/uploads
    links:
      - db
    networks:
      - back
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
